version: 0.2
phases:
  install:
    runtime-versions:
      python: latest
  build:
    commands:
      - sam build 
  post_build:
    commands:
      - sam deploy --stack-name sam-test-v2 --config-env master
# artifacts:
#   files:
#     - template.yaml
