version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - sam build 
  post_build:
    commands:
      - sam deploy --template-file template.yaml --stack-name sam-test-v2-stack --config-env master --capabilities CAPABILITY_IAM
# artifacts:
#   files:
#     - template.yaml
